# Generated by Django 5.2.17 on 2026-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cohort_classmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
