# Generated by Django 5.2.17 on 2026-09-15 07:32

import core.models
import secrets
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_codes(apps, schema_editor):
    Cohort = apps.get_model('core', 'Cohort')
    cohorts = Cohort.objects.using(schema_editor.connection.alias)
    for cohort in cohorts.all().iterator():
        code = secrets.token_hex(5).upper()
        while cohorts.filter(student_login_code=code).exists():
            code = secrets.token_hex(5).upper()
        cohort.student_login_code = code
        cohort.save(update_fields=['student_login_code'], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authratebucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='student_login_code',
            field=models.CharField(null=True, editable=False, max_length=10, unique=True),
        ),
        migrations.RunPython(assign_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cohort',
            name='student_login_code',
            field=models.CharField(default=core.models.student_login_code, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('teacher', '教師'), ('student', '學生')], default='teacher', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('student_number', models.CharField(max_length=64)),
                ('avatar', models.CharField(choices=[('cat', '貓'), ('dog', '狗'), ('rabbit', '兔')], max_length=10)),
                ('must_change_password', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.cohort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seat_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentCreatedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_events', to='core.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('cohort', 'student_number'), name='student_number_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('cohort', 'seat_number'), name='seat_number_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gte', 1), ('seat_number__lte', 9999)), name='student_seat_range'),
        ),
    ]
