# Generated by Django 5.2.17 on 2026-09-19 12:53

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_codes(apps, schema_editor):
    Cohort = apps.get_model("core", "Cohort")
    for cohort in Cohort.objects.using(schema_editor.connection.alias).all().iterator():
        cohort.application_code = core.models.teacher_application_code()
        cohort.save(using=schema_editor.connection.alias, update_fields=["application_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_student_audit_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="classmember",
            name="inactive_status",
            field=models.CharField(
                choices=[("pending", "待審核"), ("rejected", "已拒絕"), ("removed", "已移除")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="classmember",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cohort",
            name="application_code",
            field=models.CharField(null=True, editable=False, max_length=18, unique=True),
        ),
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cohort",
            name="application_code",
            field=models.CharField(
                default=core.models.teacher_application_code,
                editable=False,
                max_length=18,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="TeacherAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_name", models.CharField(max_length=80)),
                ("teacher_name", models.CharField(blank=True, max_length=80)),
                ("action", models.CharField(max_length=20)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_events",
                        to="core.cohort",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.classmember",
                    ),
                ),
            ],
        ),
    ]
