# Generated by Django 5.2.17 on 2026-09-22 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classmember_inactive_status_classmember_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='behavior_score_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('positive', '加分'), ('negative', '扣分')], max_length=8)),
                ('score', models.SmallIntegerField()),
                ('template', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=80)),
                ('action', models.CharField(default='created', max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.scorerecord')),
            ],
        ),
    ]
