# Generated by Django 5.2.17 on 2026-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_score_request_identity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scorerecord',
            name='score_request_once',
        ),
        migrations.AddField(
            model_name='scoreauditevent',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scoreauditevent',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='scorerecord',
            constraint=models.UniqueConstraint(fields=('cohort', 'creator', 'request_id', 'student'), name='score_student_request_once'),
        ),
    ]
