# Generated by Django 5.2.17 on 2026-09-26 18:24

from django.db import migrations, models


def mark_filled_reasons(apps, schema_editor):
    records = apps.get_model('core', 'ScoreRecord')
    events = apps.get_model('core', 'ScoreAuditEvent')
    changed = events.objects.filter(action='reason_filled').values('record_id')
    records.objects.filter(pk__in=changed).update(is_modified=True, individually_modified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_batch_scores_and_reason_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='individually_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(mark_filled_reasons, migrations.RunPython.noop),
    ]
