# Generated by Django 5.2.17 on 2026-09-27 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_score_revision_and_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="point_balance",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PointAwardBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_name", models.CharField(max_length=80)),
                ("request_id", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("item_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cohort"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("points", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.pointawardbatch",
                    ),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award",
                        to="core.scorerecord",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to="core.student",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pointawardbatch",
            constraint=models.UniqueConstraint(
                fields=("cohort", "actor", "request_id"), name="point_award_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="pointtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gte", 1), ("points__lte", 100)),
                name="award_points_range",
            ),
        ),
    ]
