# Generated by Django 5.2.17 on 2026-09-28 16:58

import core.models
import django.db.models.deletion
from django.db import migrations, models
import secrets


def populate_mascots(apps, schema_editor):
    Cohort = apps.get_model('core', 'Cohort')
    Mascot = apps.get_model('core', 'Mascot')
    alias = schema_editor.connection.alias
    for cohort_id in Cohort.objects.using(alias).values_list('pk', flat=True).iterator():
        Mascot.objects.using(alias).create(
            cohort_id=cohort_id, animal=secrets.choice(['cat', 'dog', 'rabbit'])
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_point_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('cat', '貓'), ('dog', '狗'), ('rabbit', '兔')], default=core.models.mascot_animal, max_length=10)),
                ('exp', models.PositiveBigIntegerField(default=0)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascot', to='core.cohort')),
            ],
        ),
        migrations.RunPython(populate_mascots, migrations.RunPython.noop),
    ]
