# Generated by Django 5.2.17 on 2026-09-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mascots'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointtransaction',
            name='award_points_range',
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='kind',
            field=models.CharField(choices=[('award', '獲得點數'), ('feed', '餵食')], default='award', max_length=8),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.pointawardbatch'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='points',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', to='core.scorerecord'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', False), ('kind', 'award'), ('points__gte', 1), ('points__lte', 100), ('record__isnull', False), ('request_id__isnull', True)), models.Q(('batch__isnull', True), ('kind', 'feed'), ('points__gte', -5), ('points__lte', -1), ('record__isnull', True), ('request_id__isnull', False)), _connector='OR'), name='point_transaction_kind_range'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.UniqueConstraint(fields=('student', 'request_id'), name='student_feed_request_once'),
        ),
    ]
