# Generated by Django 5.2.17 on 2026-09-29 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.announcement')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cohort')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cohort', 'actor', 'request_id'), name='announcement_request_once')],
            },
        ),
    ]
