# Generated by Django 5.2.17 on 2026-09-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_studentimportissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentimportissue",
            name="draft_raw",
            field=models.TextField(blank=True),
        ),
    ]
